---
title: "Untitled"
author: "Uwe Hadler"
date: "11 2 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

hotels <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv')

library(tidyverse)
library(ggplot2)
library(ggforce)
library(extrafont)
loadfonts()

```


```{r dfs, include=FALSE}

parallel_set <- hotels %>%
  filter(children <= 3, babies <=2, !is.na(children), !is.na(babies)) %>%
  mutate(kids = as.character(children+babies),
         is_cancelled = ifelse(is_canceled == 0, "Not Cancelled", "Cancelled"),
         meal = ifelse(meal %in% c("SC", "Undefined"), "NONE", meal)) %>%
  select(hotel, is_cancelled, kids, meal, customer_type) %>%
  group_by(hotel, is_cancelled, kids, meal, customer_type) %>%
  summarize(value = n()) %>%
  gather_set_data(x = c(1, 3:5))

```


```{r plots, include=FALSE}

ggplot(parallel_set, aes(x = x, id = id, split = y, value = value)) + theme_minimal() +
  geom_parallel_sets(aes(fill = is_cancelled), axis.width = 0.1, alpha = 0.66) + 
  geom_parallel_sets_axes(axis.width = 0.1, fill = "lightgrey") + 
  geom_parallel_sets_labels(colour = "black", angle = 0, family="Calibri", fontface = "bold") +
  coord_flip() + 
  scale_x_discrete(labels = c("meal" = "Meal type",
                              "kids" = "Number of kids",
                              "hotel" = "Hotel Type",
                              "customer_type" = "Customer Type"), expand = c(0,0)) +
  scale_y_continuous(breaks = seq(0, 200000, 50000), labels = scales::comma, expand = c(0.025,0.05)) +
  labs (x=NULL, y=NULL, 
        title = "Hotel cancellations",
        caption = "Visualization: Uwe Hadler | #TidyTuesday 2020 Week 7 | Source: Antonio, Almeida and Nunes, 2019") + 
  guides(fill = guide_legend(direction = "horizontal")) + 
  theme(text = element_text(family="Calibri"),
        plot.title = element_text(face="bold", size=14),
        plot.subtitle = element_text(size=12),
        legend.position = c(0.98, 1.025),
        legend.justification = "right",
        legend.title = element_blank(),
        panel.grid.major.y = element_blank())

ggsave(path = "output", filename="2020-02-11__hotels.png", dpi = 400, width = 10, height = 7, type="cairo")

```


